# Generated by Django 3.2.6 on 2021-09-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(verbose_name='date&time'),
        ),
    ]
