# Generated by Django 3.2.6 on 2021-09-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0002_alter_comment_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
