# Generated by Django 3.2.6 on 2021-08-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='vote_quantity',
        ),
    ]
