# Generated by Django 3.2.6 on 2021-09-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionApp', '0002_remove_choice_vote_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name_plural': 'Votes'},
        ),
    ]
